// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'AntDesign:caretUpFilled': typeof import('~icons/ant-design/caret-up-filled')['default']
    'AntDesign:closeCircleFilled': typeof import('~icons/ant-design/close-circle-filled')['default']
    BxErrorCircle: typeof import('~icons/bx/error-circle')['default']
    'Codicon:error': typeof import('~icons/codicon/error')['default']
    'EosIcons:loading': typeof import('~icons/eos-icons/loading')['default']
  }
}
